services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    restart: unless-stopped
    networks:
      - backend_network

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: 12345678
    volumes:
      - minio_data:/data
    restart: unless-stopped
    networks:
      - backend_network
    command: server /data --console-address ":9001"

  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      PGDATA: /data/postgres
    volumes:
       - pg_data:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - backend_network
    restart: unless-stopped
    
networks:
  backend_network:
    driver: bridge

volumes:
  minio_data:
  pg_data:  