services:
  # api:
  #   container_name:  webapi
  #   ports:
  #     - "5000:5000"
  #   depends_on:
  #     - postgres
  #   build:
  #     context: ./MRent.WebApi
  #     dockerfile: ./Dockerfile
  #   environment:
  #     - ConnectionStrings__DefaultConnection=Server=postgres_db_container;Port=5432;Database=StudentManagementDB;Username=postgres;Password=12345678;
  #     - ASPNETCORE_URLS=http://+:5000
  #   networks:
  #     - mrent_network
  #   command: ["dotnet", "ef", "database update"]

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    restart: unless-stopped
    networks:
      - backend_network

  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      PGDATA: /data/postgres
    volumes:
       - pg_data:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - backend_network
    restart: unless-stopped
    
networks:
  backend_network:
    driver: bridge

volumes:
  pg_data: